url: "https://ludoenso.github.io"

#header_pages:
  - index.md
  - about.md


#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
