title: 'ludoenso.github.io'
description: "Ludovic Vanasse's blog"
baseurl: ""
url: "https://ludoenso.github.io"

header_pages:
  - index.md
  - about.md


style: dark

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console